# Generated by Django 5.0.1 on 2024-01-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeproduct',
            name='product_weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Вес продукта в граммах'),
        ),
    ]
